interface EventsFields {
	AFTER_CHILD_ADDED: string;
	AFTER_CHILD_CHANGED: string;
	AFTER_CHILD_REMOVED: string;
	AFTER_PARENT_ADDED: string;
	AFTER_PARENT_CHANGED: string;
	AFTER_PARENT_REMOVED: string;
	BEFORE_CHILD_ADDED: string;
	BEFORE_CHILD_CHANGED: string;
	BEFORE_CHILD_REMOVED: string;
	BEFORE_DISPOSE: string;
	BEFORE_PARENT_ADDED: string;
	BEFORE_PARENT_CHANGED: string;
	BEFORE_PARENT_REMOVED: string;
	COMPONENT_NESTING_CHANGED: string;
	CYDRAN_PREAPP_DISPOSAL: string;
}

const Events: EventsFields = {
	AFTER_CHILD_ADDED: "AFTER_CHILD_ADDED",
	AFTER_CHILD_CHANGED: "AFTER_CHILD_CHANGED",
	AFTER_CHILD_REMOVED: "AFTER_CHILD_REMOVED",
	AFTER_PARENT_ADDED: "AFTER_PARENT_ADDED",
	AFTER_PARENT_CHANGED: "AFTER_PARENT_CHANGED",
	AFTER_PARENT_REMOVED: "AFTER_PARENT_REMOVED",
	BEFORE_CHILD_ADDED: "BEFORE_CHILD_ADDED",
	BEFORE_CHILD_CHANGED: "BEFORE_CHILD_CHANGED",
	BEFORE_CHILD_REMOVED: "BEFORE_CHILD_REMOVED",
	BEFORE_DISPOSE: "BEFORE_DISPOSE",
	BEFORE_PARENT_ADDED: "BEFORE_PARENT_ADDED",
	BEFORE_PARENT_CHANGED: "BEFORE_PARENT_CHANGED",
	BEFORE_PARENT_REMOVED: "BEFORE_PARENT_REMOVED",
	COMPONENT_NESTING_CHANGED: "COMPONENT_NESTING_CHANGED",
	CYDRAN_PREAPP_DISPOSAL: "CYDRAN_PREAPP_DISPOSAL"
};

export default Events;