enum BehaviorFlags {
	ROOT_PROHIBITED = "ROOT_PROHIBITED",
	PROPAGATION = "PROPAGATION",
	CHILD_CONSUMPTION_PROHIBITED = "CHILD_CONSUMPTION_PROHIBITED",
	EXPRESSION_DISALLOWED = "EXPRESSION_DISALLOWED"
}

export default BehaviorFlags;
