enum ComponentState {
	BOOTSTRAPPED = "BOOTSTRAPPED",
	VALIDATED = "VALIDATED",
	UNINITIALIZED = "UNINITIALIZED",
	INITIALIZED = "INITIALIZED",
	READY = "READY",
	MOUNTED = "MOUNTED",
	UNMOUNTED = "UNMOUNTED",
	DISPOSED = "DISPOSED"
}

export default ComponentState;
