enum MediatorState {
	UNINITIALIZED = "UNINITIALIZED",
	INITIALIZED = "INITIALIZED",
	READY = "READY",
	MOUNTED = "MOUNTED",
	UNMOUNTED = "UNMOUNTED",
	DISPOSED = "DISPOSED"
}

export default MediatorState;
