import { argumentsBuilder, Context } from "@cydran/cydran";
import Intro from "./Intro";
import Validation from "./Validation";
import Regions from "./Regions";
import InlineComponent from "./regions/InlineComponent";
import RadioButtons from "./RadioButtons";
import MultiSelects from "./MultiSelects";
import SharedModel from "./SharedModel";
import ReadOnly from "./ReadOnly";
import Svg from "./Svg";
import CheckboxState from "./CheckboxState";
import Modals from "./Modals";
import WatchedField from "./WatchedField";
import FocusedEach from "./FocusedEach";
import Clock from "./Clock";
import WebComponentExample from "./WebComponentExample";
import FormElements from "./FormElements";
import Logging from "./Logging";
import TypedInputs from "./TypedInputs";
import InputModelBehaviorTextSpecimen from "./InputModelBehaviorTextSpecimen";
import InputModelBehaviorTextareaSpecimen from "./InputModelBehaviorTextareaSpecimen";
import InputModelBehaviorNumberSpecimen from "./InputModelBehaviorNumberSpecimen";
import InputModelBehaviorRangeSpecimen from "./InputModelBehaviorRangeSpecimen";
import InputModelBehaviorDateSpecimen from "./InputModelBehaviorDateSpecimen";
import InputModelBehaviorTextTypesSpecimen from "./InputModelBehaviorTextTypesSpecimen";
import InputModelBehaviorColorSpecimen from "./InputModelBehaviorColorSpecimen";
import IfBehaviorSpecimen from "./IfBehaviorSpecimen";
import HiddenBehaviorSpecimen from "./HiddenBehaviorSpecimen";
import EnabledBehaviorSpecimen from "./EnabledBehaviorSpecimen";
import CssClassBehaviorSpecimen from "./CssClassBehaviorSpecimen";
import StyleBehaviorSpecimen from "./StyleBehaviorSpecimen";
import IdBehaviorSpecimen from "./IdBehaviorSpecimen";
import EventBehaviorSpecimen from "./EventBehaviorSpecimen";
import ReadOnlyBehaviorSpecimen from "./ReadOnlyBehaviorSpecimen";
import RequiredBehaviorSpecimen from "./RequiredBehaviorSpecimen";
import InertBehaviorSpecimen from "./InertBehaviorSpecimen";
import CheckedBehaviorSpecimen from "./CheckedBehaviorSpecimen";
import FocusBehaviorSpecimen from "./FocusBehaviorSpecimen";
import TextBehaviorSpecimen from "./TextBehaviorSpecimen";
import AttributeBehaviorSpecimen from "./AttributeBehaviorSpecimen";
import FormBehaviorSpecimen from "./FormBehaviorSpecimen";
import SeriesBehaviorSpecimen from "./SeriesBehaviorSpecimen";
import RegionBehaviorSpecimen from "./RegionBehaviorSpecimen";
import RegionDiChild from "./RegionDiChild";
import EachBehaviorSpecimen from "./EachBehaviorSpecimen";
import ErrorCatalogSpecimen from "./ErrorCatalogSpecimen";
import InputModelBehaviorSelectSpecimen from "./InputModelBehaviorSelectSpecimen";
import InputModelBehaviorSelectMultipleSpecimen from "./InputModelBehaviorSelectMultipleSpecimen";
import InputModelBehaviorRadioSpecimen from "./InputModelBehaviorRadioSpecimen";
import ValidatedBehaviorSpecimen from "./ValidatedBehaviorSpecimen";
import NotYetImplemented from "./NotYetImplemented";

function specimensCapability(context: Context) {
	context.registerPrototype("intro", Intro);
	context.registerPrototype("notyetimplemented", NotYetImplemented);
	context.registerPrototype("regions", Regions);
	context.registerPrototype("validation", Validation);
	context.registerPrototype("radioButtons", RadioButtons);
	context.registerPrototype("multiSelects", MultiSelects);
	context.registerPrototype("sharedModel", SharedModel);
	context.registerPrototype("readOnly", ReadOnly);
	context.registerPrototype("svg", Svg);
	context.registerPrototype("checkboxState", CheckboxState);
	context.registerPrototype("modals", Modals);
	context.registerPrototype("watchedField", WatchedField);
	context.registerPrototype("focusedEach", FocusedEach);
	context.registerPrototype("clock", Clock);
	context.registerPrototype("inline", InlineComponent);
	context.registerPrototype("webComponentExample", WebComponentExample);
	context.registerPrototype("formElements", FormElements);
	context.registerPrototype("typedInputs", TypedInputs);
	context.registerPrototype("inputModelBehaviorText", InputModelBehaviorTextSpecimen);
	context.registerPrototype("inputModelBehaviorTextarea", InputModelBehaviorTextareaSpecimen);
	context.registerPrototype("inputModelBehaviorNumber", InputModelBehaviorNumberSpecimen);
	context.registerPrototype("inputModelBehaviorRange", InputModelBehaviorRangeSpecimen);
	context.registerPrototype("inputModelBehaviorDate", InputModelBehaviorDateSpecimen);
	context.registerPrototype("inputModelBehaviorTextTypes", InputModelBehaviorTextTypesSpecimen);
	context.registerPrototype("inputModelBehaviorColor", InputModelBehaviorColorSpecimen);
	context.registerPrototype("ifBehavior", IfBehaviorSpecimen);
	context.registerPrototype("hiddenBehavior", HiddenBehaviorSpecimen);
	context.registerPrototype("enabledBehavior", EnabledBehaviorSpecimen);
	context.registerPrototype("cssClassBehavior", CssClassBehaviorSpecimen);
	context.registerPrototype("styleBehavior", StyleBehaviorSpecimen);
	context.registerPrototype("idBehavior", IdBehaviorSpecimen);
	context.registerPrototype("eventBehavior", EventBehaviorSpecimen);
	context.registerPrototype("readOnlyBehavior", ReadOnlyBehaviorSpecimen);
	context.registerPrototype("requiredBehavior", RequiredBehaviorSpecimen);
	context.registerPrototype("inertBehavior", InertBehaviorSpecimen);
	context.registerPrototype("checkedBehavior", CheckedBehaviorSpecimen);
	context.registerPrototype("focusBehavior", FocusBehaviorSpecimen);
	context.registerPrototype("textBehavior", TextBehaviorSpecimen);
	context.registerPrototype("attributeBehavior", AttributeBehaviorSpecimen);
	context.registerPrototype("formBehavior", FormBehaviorSpecimen);
	context.registerPrototype("seriesBehavior", SeriesBehaviorSpecimen);
	context.registerPrototype("regionBehavior", RegionBehaviorSpecimen);
	context.registerPrototype("regionDiChild", RegionDiChild);
	context.registerPrototype("eachBehavior", EachBehaviorSpecimen);
	context.registerPrototype("errorCatalog", ErrorCatalogSpecimen);
	context.registerPrototype("inputModelBehaviorSelect", InputModelBehaviorSelectSpecimen);
	context.registerPrototype("inputModelBehaviorSelectMultiple", InputModelBehaviorSelectMultipleSpecimen);
	context.registerPrototype("inputModelBehaviorRadio", InputModelBehaviorRadioSpecimen);
	context.registerPrototype("validatedBehavior", ValidatedBehaviorSpecimen);
	context.registerPrototype("logging", Logging, argumentsBuilder().withLogger("testLogger").build());
}

export { specimensCapability };
