enum ContextStates {
	UNINITIALIZED = "UNINITIALIZED",
	BOOTSTRAPPED = "BOOTSTRAPPED",
	STARTING = "STARTING",
	READY = "READY",
	DISPOSING = "DISPOSING",
	DISPOSED = "DISPOSED"
}

export default ContextStates;
