import {Mvvm} from "../Core";

import AttributeElementDecorator from "./AttributeDecorator";
import CheckboxListDecorator from "./CheckboxListDecorator";
import ComponentEachElementDecorator from "./ComponentEachDecorator";
import DisableableModelElementDecorator from "./DisableableModelDecorator";
import ForceFocusElementDecorator from "./ForceFocusDecorator";
import InnerHtmlElementDecorator from "./InnerHtmlDecorator";
import RegionDecorator from "./RegionDecorator";
import SelectOptionsElementDecorator from "./SelectOptionsDecorator";
import ValuedModelElementDecorator from "./ValuedModelDecorator";
import VisibleElementDecorator from "./VisibleDecorator";

import AuxClickEventDecorator from "./event/mouse/AuxClickEventDecorator";
import ClickEventDecorator from "./event/mouse/ClickEventDecorator";
import ContextMenuEventDecorator from "./event/mouse/ContextMenuEventDecorator";
import DblClickEventDecorator from "./event/mouse/DblClickEventDecorator";
import DragEventDecorator from "./event/mouse/DragEventDecorator";
import DragEndEventDecorator from "./event/mouse/DragEndEventDecorator";
import DragEnterEventDecorator from "./event/mouse/DragEnterEventDecorator";
import DragLeaveEventDecorator from "./event/mouse/DragLeaveEventDecorator";
import DragOverEventDecorator from "./event/mouse/DragOverEventDecorator";
import DragStartEventDecorator from "./event/mouse/DragStartEventDecorator";
import DropEventDecorator from "./event/mouse/DragStartEventDecorator";
import MouseDownEventDecorator from "./event/mouse/MouseDownEventDecorator";
import MouseMoveEventDecorator from "./event/mouse/MouseMoveEventDecorator";
import MouseOutEventDecorator from "./event/mouse/MouseOutEventDecorator";
import MouseOverEventDecorator from "./event/mouse/MouseOverEventDecorator";
import MouseUpEventDecorator from "./event/mouse/MouseUpEventDecorator";
import MouseWheelEventDecorator from "./event/mouse/MouseWheelEventDecorator";
import ScrollEventDecorator from "./event/mouse/ScrollEventDecorator";
import ShowEventDecorator from "./event/mouse/ShowEventDecorator";
import ToggleEventDecorator from "./event/mouse/ToggleEventDecorator";
import WheelEventDecorator from "./event/mouse/WheelEventDecorator";
import KeyDownEventDecorator from "./event/keyboard/KeyDownEventDecorator";
import KeyPressEventDecorator from "./event/keyboard/KeyPressEventDecorator";
import KeyUpEventDecorator from "./event/keyboard/KeyUpEventDecorator";
import BlurEventDecorator from "./event/dom/BlurEventDecorator";
import ChangeEventDecorator from "./event/dom/ChangeEventDecorator";
import CopyEventDecorator from "./event/dom/CopyEventDecorator";
import CutEventDecorator from "./event/dom/CutEventDecorator";
import FocusEventDecorator from "./event/dom/FocusEventDecorator";
import HashChangeEventDecorator from "./event/dom/HashChangeEventDecorator";
import InputEventDecorator from "./event/dom/InputEventDecorator";
import InvalidEventDecorator from "./event/dom/InvalidEventDecorator";
import LoadEventDecorator from "./event/dom/LoadEventDecorator";
import MessageEventDecorator from "./event/dom/MessageEventDecorator";
import PasteEventDecorator from "./event/dom/PasteEventDecorator";
import ResizeEventDecorator from "./event/dom/ResizeEventDecorator";
import SelectEventDecorator from "./event/dom/SelectEventDecorator";
import UnloadEventDecorator from "./event/dom/UnlodEventDecorator";
import WindowErrorEventDecorator from "./event/dom/WindowErrorEventDecorator";
import ResetEventDecorator from "./event/form/ResetEventDecorator";
import SubmitEventDecorator from "./event/form/SubmitEventDecorator";

Mvvm.register("auxclick", ["*"], AuxClickEventDecorator);
Mvvm.register("blur", ["*"], BlurEventDecorator);
Mvvm.register("change", ["*"], ChangeEventDecorator);
Mvvm.register("click", ["*"], ClickEventDecorator);
Mvvm.register("contextmenu", ["*"], ContextMenuEventDecorator);
Mvvm.register("copy", ["*"], CopyEventDecorator);
Mvvm.register("cut", ["*"], CutEventDecorator);
Mvvm.register("dblclick", ["*"], DblClickEventDecorator);
Mvvm.register("drag", ["*"], DragEventDecorator);
Mvvm.register("dragend", ["*"], DragEndEventDecorator);
Mvvm.register("dragenter", ["*"], DragEnterEventDecorator);
Mvvm.register("dragleave", ["*"], DragLeaveEventDecorator);
Mvvm.register("dragover", ["*"], DragOverEventDecorator);
Mvvm.register("dragstart", ["*"], DragStartEventDecorator);
Mvvm.register("drop", ["*"], DropEventDecorator);
Mvvm.register("focus", ["*"], FocusEventDecorator);
Mvvm.register("hashchange", ["*"], HashChangeEventDecorator);
Mvvm.register("input", ["*"], InputEventDecorator);
Mvvm.register("invalid", ["*"], InvalidEventDecorator);
Mvvm.register("keydown", ["*"], KeyDownEventDecorator);
Mvvm.register("keypress", ["*"], KeyPressEventDecorator);
Mvvm.register("keyup", ["*"], KeyUpEventDecorator);
Mvvm.register("load", ["*"], LoadEventDecorator);
Mvvm.register("message", ["*"], MessageEventDecorator);
Mvvm.register("mousedown", ["*"], MouseDownEventDecorator);
Mvvm.register("mousemove", ["*"], MouseMoveEventDecorator);
Mvvm.register("mouseout", ["*"], MouseOutEventDecorator);
Mvvm.register("mouseover", ["*"], MouseOverEventDecorator);
Mvvm.register("mouseup", ["*"], MouseUpEventDecorator);
Mvvm.register("mousewheel", ["*"], MouseWheelEventDecorator);
Mvvm.register("paste", ["*"], PasteEventDecorator);
Mvvm.register("reset", ["*"], ResetEventDecorator);
Mvvm.register("resize", ["*"], ResizeEventDecorator);
Mvvm.register("scroll", ["*"], ScrollEventDecorator);
Mvvm.register("select", ["*"], SelectEventDecorator);
Mvvm.register("submit", ["*"], SubmitEventDecorator);
Mvvm.register("show", ["*"], ShowEventDecorator);
Mvvm.register("toggle", ["*"], ToggleEventDecorator);
Mvvm.register("unload", ["*"], UnloadEventDecorator);
Mvvm.register("wheel", ["*"], WheelEventDecorator);
Mvvm.register("error", ["*"], WindowErrorEventDecorator);

Mvvm.register("model", ["input", "select", "textarea"], ValuedModelElementDecorator);
Mvvm.register("model", ["span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "li", "label", "div"], InnerHtmlElementDecorator);
Mvvm.register("options-model", ["select"], SelectOptionsElementDecorator);
Mvvm.register("enabled", ["select", "input", "textarea", "button"], DisableableModelElementDecorator);
Mvvm.register("attribute", ["*"], AttributeElementDecorator);
Mvvm.register("visible", ["*"], VisibleElementDecorator);
Mvvm.register("component-each", ["*"], ComponentEachElementDecorator);
Mvvm.register("force-focus", ["*"], ForceFocusElementDecorator);
Mvvm.register("region", ["*"], RegionDecorator);
Mvvm.register("checkbox-list", ["ul"], CheckboxListDecorator);
