import { Mvvm } from "../Core";

import AttributeElementDecorator from "./AttributeDecorator";
import CheckboxListDecorator from "./CheckboxListDecorator";
import ComponentEachElementDecorator from "./ComponentEachDecorator";
import DisableableModelElementDecorator from "./DisableableModelDecorator";
import ForceFocusElementDecorator from "./ForceFocusDecorator";
import InnerHtmlElementDecorator from "./InnerHtmlDecorator";
import RegionDecorator from "./RegionDecorator";
import SelectOptionsElementDecorator from "./SelectOptionsDecorator";
import ValuedModelElementDecorator from "./ValuedModelDecorator";
import VisibleElementDecorator from "./VisibleDecorator";
import ClassDecorator from "./ClassDecorator";

import AuxClickEventDecorator from "./event/mouse/AuxClickEventDecorator";
import ClickEventDecorator from "./event/mouse/ClickEventDecorator";
import ContextMenuEventDecorator from "./event/mouse/ContextMenuEventDecorator";
import DblClickEventDecorator from "./event/mouse/DblClickEventDecorator";
import DragEventDecorator from "./event/mouse/DragEventDecorator";
import DragEndEventDecorator from "./event/mouse/DragEndEventDecorator";
import DragEnterEventDecorator from "./event/mouse/DragEnterEventDecorator";
import DragLeaveEventDecorator from "./event/mouse/DragLeaveEventDecorator";
import DragOverEventDecorator from "./event/mouse/DragOverEventDecorator";
import DragStartEventDecorator from "./event/mouse/DragStartEventDecorator";
import DropEventDecorator from "./event/mouse/DragStartEventDecorator";
import MouseDownEventDecorator from "./event/mouse/MouseDownEventDecorator";
import MouseMoveEventDecorator from "./event/mouse/MouseMoveEventDecorator";
import MouseOutEventDecorator from "./event/mouse/MouseOutEventDecorator";
import MouseOverEventDecorator from "./event/mouse/MouseOverEventDecorator";
import MouseUpEventDecorator from "./event/mouse/MouseUpEventDecorator";
import MouseWheelEventDecorator from "./event/mouse/MouseWheelEventDecorator";
import ShowEventDecorator from "./event/mouse/ShowEventDecorator";
import ToggleEventDecorator from "./event/mouse/ToggleEventDecorator";
import WheelEventDecorator from "./event/mouse/WheelEventDecorator";
import KeyDownEventDecorator from "./event/keyboard/KeyDownEventDecorator";
import KeyPressEventDecorator from "./event/keyboard/KeyPressEventDecorator";
import KeyUpEventDecorator from "./event/keyboard/KeyUpEventDecorator";
import BlurEventDecorator from "./event/dom/BlurEventDecorator";
import ChangeEventDecorator from "./event/dom/ChangeEventDecorator";
import HashChangeEventDecorator from "./event/dom/HashChangeEventDecorator";
import InputEventDecorator from "./event/dom/InputEventDecorator";
import InvalidEventDecorator from "./event/dom/InvalidEventDecorator";
import LoadEventDecorator from "./event/dom/LoadEventDecorator";
import SelectEventDecorator from "./event/dom/SelectEventDecorator";
import UnloadEventDecorator from "./event/dom/UnloadEventDecorator";
import ResetEventDecorator from "./event/form/ResetEventDecorator";
import SubmitEventDecorator from "./event/form/SubmitEventDecorator";
import AbortEventDecorator from "./event/dom/AbortEventDecorator";
import CanPlayEventDecorator from "./event/media/CanPlayEventDecorator";
import CanPlayThroughEventDecorator from "./event/media/CanPlayThroughEventDecorator";
import DurationChangeEventDecorator from "./event/media/DurationChangeEventDecorator";
import EmptiedEventDecorator from "./event/media/EmptiedEventDecorator";
import EndedEventDecorator from "./event/media/EndedEventDecorator";
import FormInputEventDecorator from "./event/form/FormInputEventDecorator";
import FormChangeEventDecorator from "./event/form/FormChangeEventDecorator";
import LoadedDataEventDecorator from "./event/media/LoadedDataEventDecorator";
import LoadedMetaDataEventDecorator from "./event/media/LoadedMetaDataEventDecorator";
import LoadStartEventDecorator from "./event/media/LoadStartEventDecorator";
import PauseEventDecorator from "./event/media/PauseEventDecorator";
import PlayEventDecorator from "./event/media/PlayEventDecorator";
import PlayingEventDecorator from "./event/media/PlayingEventDecorator";
import WaitingEventDecorator from "./event/media/WaitingEventDecorator";
import ReadyStateChangeEventDecorator from "./event/dom/ReadyStateChangeEventDecorator";
import ProgressEventDecorator from "./event/media/ProgressEventDecorator";
import RedoEventDecorator from "./event/dom/RedoEventDecorator";
import SeekedEventDecorator from "./event/media/SeekedEventDecorator";
import SeekingEventDecorator from "./event/media/SeekingEventDecorator";
import StalledEventDecorator from "./event/media/StalledEventDecorator";
import StorageEventDecorator from "./event/dom/StorageEventDecorator";
import SuspendEventDecorator from "./event/media/SuspendEventDecorator";
import TimeUpdateEventDecorator from "./event/media/TimeUpdateEventDecorator";
import UndoEventDecorator from "./event/dom/UndoEventDecorator";
import VolumeChangeEventDecorator from "./event/media/VolumeChangeEventDecorator";
import BeforeUnloadEventDecorator from "./event/dom/BeforeUnloadEventDecorator";
import RateChangeEventDecorator from "./event/media/RateChangeEventDecorator";
import SearchEventDecorator from "./event/form/SearchEventDecorator";
import TouchStartEventDecorator from "./event/mobile/TouchStartEventDecorator";
import TouchEndEventDecorator from "./event/mobile/TouchEndEventDecorator";
import TouchMoveEventDecorator from "./event/mobile/TouchMoveEventDecorator";
import TouchCancelEventDecorator from "./event/mobile/TouchCancelEventDecorator";
import OnlineEventDecorator from "./event/network/OnlineEventDecorator";
import OfflineEventDecorator from "./event/network/OfflineEventDecorator";
import FocusEventDecorator from "./event/focus/FocusEventDecorator";
import FocusInEventDecorator from "./event/focus/FocusInEventDecorator";
import FocusOutEventDecorator from "./event/focus/FocusOutEventDecorator";
import MessageEventDecorator from "./event/websocket/MessageEventDecorator";
import CloseEventDecorator from "./event/websocket/CloseEventDecorator";
import PopStateEventDecorator from "./event/session/PopStateEventDecorator";
import PageShowEventDecorator from "./event/session/PageShowEventDecorator";
import PageHideEventDecorator from "./event/session/PageHideEventDecorator";
import AfterPrintEventDecorator from "./event/print/AfterPrintEventDecorator";
import BeforePrintEventDecorator from "./event/print/BeforePrintEventDecorator";
import ScrollEventDecorator from "./event/view/ScrollEventDecorator";
import ResizeEventDecorator from "./event/view/ResizeEventDecorator";
import CopyEventDecorator from "./event/clipboard/CopyEventDecorator";
import CutEventDecorator from "./event/clipboard/CutEventDecorator";
import PasteEventDecorator from "./event/clipboard/PasteEventDecorator";
import OpenEventDecorator from "./event/network/OpenEventDecorator";
import ErrorEventDecorator from "./event/dom/ErrorEventDecorator";
import FullScreenChangeEventDecorator from "./event/view/FullScreenChangeEventDecorator";
import FullScreenErrorEventDecorator from "./event/view/FullScreenErrorEventDecorator";

Mvvm.register("undo", ["*"], UndoEventDecorator);
Mvvm.register("volumechange", ["*"], VolumeChangeEventDecorator);
Mvvm.register("timeupdate", ["*"], TimeUpdateEventDecorator);
Mvvm.register("suspend", ["*"], SuspendEventDecorator);
Mvvm.register("stalled", ["*"], StalledEventDecorator);
Mvvm.register("storage", ["*"], StorageEventDecorator);
Mvvm.register("seeking", ["*"], SeekingEventDecorator);
Mvvm.register("seeked", ["*"], SeekedEventDecorator);
Mvvm.register("redo", ["*"], RedoEventDecorator);
Mvvm.register("progress", ["*"], ProgressEventDecorator);
Mvvm.register("readystate", ["*"], ReadyStateChangeEventDecorator);
Mvvm.register("popstate", ["*"], PopStateEventDecorator);
Mvvm.register("pause", ["*"], PauseEventDecorator);
Mvvm.register("play", ["*"], PlayEventDecorator);
Mvvm.register("playing", ["*"], PlayingEventDecorator);
Mvvm.register("pageshow", ["*"], PageShowEventDecorator);
Mvvm.register("pagehide", ["*"], PageHideEventDecorator);
Mvvm.register("online", ["*"], OnlineEventDecorator);
Mvvm.register("loadstart", ["*"], LoadStartEventDecorator);
Mvvm.register("loadeddata", ["*"], LoadedDataEventDecorator);
Mvvm.register("loadedmetadata", ["*"], LoadedMetaDataEventDecorator);
Mvvm.register("offline", ["*"], OfflineEventDecorator);
Mvvm.register("formchange", ["*"], FormChangeEventDecorator);
Mvvm.register("forminput", ["*"], FormInputEventDecorator);
Mvvm.register("ended", ["*"], EndedEventDecorator);
Mvvm.register("emptied", ["*"], EmptiedEventDecorator);
Mvvm.register("durationchange", ["*"], DurationChangeEventDecorator);
Mvvm.register("canplaythrough", ["*"], CanPlayThroughEventDecorator);
Mvvm.register("canplay", ["*"], CanPlayEventDecorator);
Mvvm.register("beforeunload", ["*"], BeforeUnloadEventDecorator);
Mvvm.register("afterprint", ["*"], AfterPrintEventDecorator);
Mvvm.register("beforeprint", ["*"], BeforePrintEventDecorator);
Mvvm.register("offline", ["*"], OfflineEventDecorator);
Mvvm.register("abort", ["*"], AbortEventDecorator);
Mvvm.register("auxclick", ["*"], AuxClickEventDecorator);
Mvvm.register("blur", ["*"], BlurEventDecorator);
Mvvm.register("change", ["*"], ChangeEventDecorator);
Mvvm.register("click", ["*"], ClickEventDecorator);
Mvvm.register("contextmenu", ["*"], ContextMenuEventDecorator);
Mvvm.register("copy", ["*"], CopyEventDecorator);
Mvvm.register("cut", ["*"], CutEventDecorator);
Mvvm.register("dblclick", ["*"], DblClickEventDecorator);
Mvvm.register("drag", ["*"], DragEventDecorator);
Mvvm.register("dragend", ["*"], DragEndEventDecorator);
Mvvm.register("dragenter", ["*"], DragEnterEventDecorator);
Mvvm.register("dragleave", ["*"], DragLeaveEventDecorator);
Mvvm.register("dragover", ["*"], DragOverEventDecorator);
Mvvm.register("dragstart", ["*"], DragStartEventDecorator);
Mvvm.register("drop", ["*"], DropEventDecorator);
Mvvm.register("focus", ["*"], FocusEventDecorator);
Mvvm.register("focusin", ["*"], FocusInEventDecorator);
Mvvm.register("focusout", ["*"], FocusOutEventDecorator);
Mvvm.register("hashchange", ["*"], HashChangeEventDecorator);
Mvvm.register("input", ["*"], InputEventDecorator);
Mvvm.register("invalid", ["*"], InvalidEventDecorator);
Mvvm.register("keydown", ["*"], KeyDownEventDecorator);
Mvvm.register("keypress", ["*"], KeyPressEventDecorator);
Mvvm.register("keyup", ["*"], KeyUpEventDecorator);
Mvvm.register("load", ["*"], LoadEventDecorator);
Mvvm.register("message", ["*"], MessageEventDecorator);
Mvvm.register("mousedown", ["*"], MouseDownEventDecorator);
Mvvm.register("mousemove", ["*"], MouseMoveEventDecorator);
Mvvm.register("mouseout", ["*"], MouseOutEventDecorator);
Mvvm.register("mouseover", ["*"], MouseOverEventDecorator);
Mvvm.register("mouseup", ["*"], MouseUpEventDecorator);
Mvvm.register("mousewheel", ["*"], MouseWheelEventDecorator);
Mvvm.register("paste", ["*"], PasteEventDecorator);
Mvvm.register("reset", ["*"], ResetEventDecorator);
Mvvm.register("resize", ["*"], ResizeEventDecorator);
Mvvm.register("scroll", ["*"], ScrollEventDecorator);
Mvvm.register("select", ["*"], SelectEventDecorator);
Mvvm.register("submit", ["*"], SubmitEventDecorator);
Mvvm.register("show", ["*"], ShowEventDecorator);
Mvvm.register("toggle", ["*"], ToggleEventDecorator);
Mvvm.register("unload", ["*"], UnloadEventDecorator);
Mvvm.register("wheel", ["*"], WheelEventDecorator);
Mvvm.register("error", ["*"], ErrorEventDecorator);
Mvvm.register("fullscreenchange", ["*"], FullScreenChangeEventDecorator);
Mvvm.register("fullscreenerror", ["*"], FullScreenErrorEventDecorator);
Mvvm.register("open", ["*"], OpenEventDecorator);
Mvvm.register("close", ["*"], CloseEventDecorator);
Mvvm.register("ratechange", ["*"], RateChangeEventDecorator);
Mvvm.register("search", ["*"], SearchEventDecorator);
Mvvm.register("touchstart", ["*"], TouchStartEventDecorator);
Mvvm.register("touchend", ["*"], TouchEndEventDecorator);
Mvvm.register("touchmove", ["*"], TouchMoveEventDecorator);
Mvvm.register("touchcancel", ["*"], TouchCancelEventDecorator);
Mvvm.register("waiting", ["*"], WaitingEventDecorator);

Mvvm.register("model", ["input", "select", "textarea"], ValuedModelElementDecorator);
Mvvm.register("model", ["span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "li", "label", "div"], InnerHtmlElementDecorator);
Mvvm.register("options-model", ["select"], SelectOptionsElementDecorator);
Mvvm.register("enabled", ["select", "input", "textarea", "button"], DisableableModelElementDecorator);
Mvvm.register("attribute", ["*"], AttributeElementDecorator);
Mvvm.register("visible", ["*"], VisibleElementDecorator);
Mvvm.register("class", ["*"], ClassDecorator);
Mvvm.register("component-each", ["*"], ComponentEachElementDecorator);
Mvvm.register("force-focus", ["*"], ForceFocusElementDecorator);
Mvvm.register("region", ["*"], RegionDecorator);
Mvvm.register("checkbox-list", ["ul"], CheckboxListDecorator);
