import {Mvvm} from "../Core";

import AttributeElementDecorator from "./AttributeDecorator";
import CheckboxListDecorator from "./CheckboxListDecorator";
import ComponentEachElementDecorator from "./ComponentEachDecorator";
import DisableableModelElementDecorator from "./DisableableModelDecorator";
import ForceFocusElementDecorator from "./ForceFocusDecorator";
import InnerHtmlElementDecorator from "./InnerHtmlDecorator";
import RegionDecorator from "./RegionDecorator";
import SelectOptionsElementDecorator from "./SelectOptionsDecorator";
import ValuedModelElementDecorator from "./ValuedModelDecorator";
import VisibleElementDecorator from "./VisibleDecorator";

import ClickElementDecorator from "./event/mouse/ClickDecorator";
import AuxClickElementDecorator from "./event/mouse/AuxClickDecorator";
import ContextMenuDecorator from "./event/mouse/ContextMenuDecorator";
import DblClickElementDecorator from "./event/mouse/DblClickElementDecorator";
import DragElementDecorator from "./event/mouse/DragElementDecorator";
import DragEndElementDecorator from "./event/mouse/DragEndElementDecorator";
import DragEnterElementDecorator from "./event/mouse/DragEnterElementDecorator";
import DragLeaveElementDecorator from "./event/mouse/DragLeaveElementDecorator";
import DragOverElementDecorator from "./event/mouse/DragOverElementDecorator";
import DragStartElementDecorator from "./event/mouse/DragStartElementDecorator";
import DropElementDecorator from "./event/mouse/DragStartElementDecorator";
import MouseDownElementDecorator from "./event/mouse/MouseDownElementDecorator";
import MouseMoveElementDecorator from "./event/mouse/MouseMoveElementDecorator";
import MouseOutElementDecorator from "./event/mouse/MouseOutElementDecorator";
import MouseOverElementDecorator from "./event/mouse/MouseOverElementDecorator";
import MouseUpElementDecorator from "./event/mouse/MouseUpElementDecorator";
import MouseWheelElementDecorator from "./event/mouse/MouseWheelElementDecorator";
import ScrollElementDecorator from "./event/mouse/ScrollElementDecorator";
import ShowElementDecorator from "./event/mouse/ShowElementDecorator";
import ToggleElementDecorator from "./event/mouse/ToggleElementDecorator";
import WheelElementDecorator from "./event/mouse/WheelElementDecorator";
import KeyDownElementDecorator from "./event/keyboard/KeyDownDecorator";
import KeyPressElementDecorator from "./event/keyboard/KeyPressDecorator";
import KeyUpElementDecorator from "./event/keyboard/KeyUpDecorator";
import BlurDecorator from "./event/form/BlurDecorator";
import ChangeDecorator from "./event/form/ChangeDecorator";
import FocusDecorator from "./event/form/FocusDecorator";
import InputDecorator from "./event/form/InputDecorator";
import InvalidDecorator from "./event/form/InvalidDecorator";

Mvvm.register("blur", ["*"], BlurDecorator);
Mvvm.register("change", ["*"], ChangeDecorator);
Mvvm.register("focus", ["*"], FocusDecorator);
Mvvm.register("input", ["*"], InputDecorator);
Mvvm.register("invalid", ["*"], InputDecorator);
Mvvm.register("click", ["*"], ClickElementDecorator);
Mvvm.register("auxclick", ["*"], AuxClickElementDecorator);
Mvvm.register("dblclick", ["*"], ComponentEachElementDecorator);
Mvvm.register("contextmenu", ["*"], ContextMenuDecorator);
Mvvm.register("drag", ["*"], DragElementDecorator);
Mvvm.register("dragend", ["*"], DragEndElementDecorator);
Mvvm.register("dragenter", ["*"], DragEnterElementDecorator);
Mvvm.register("dragleave", ["*"], DragLeaveElementDecorator);
Mvvm.register("dragover", ["*"], DragOverElementDecorator);
Mvvm.register("dragstart", ["*"], DragStartElementDecorator);
Mvvm.register("drop", ["*"], DropElementDecorator);
Mvvm.register("mousedown", ["*"], MouseDownElementDecorator);
Mvvm.register("mousemove", ["*"], MouseMoveElementDecorator);
Mvvm.register("mouseout", ["*"], MouseOutElementDecorator);
Mvvm.register("mouseover", ["*"], MouseOverElementDecorator);
Mvvm.register("mouseup", ["*"], MouseUpElementDecorator);
Mvvm.register("mousewheel", ["*"], MouseWheelElementDecorator);
Mvvm.register("keydown", ["*"], KeyDownElementDecorator);
Mvvm.register("keypress", ["*"], KeyPressElementDecorator);
Mvvm.register("keyup", ["*"], KeyUpElementDecorator);

Mvvm.register("model", ["input", "select", "textarea"], ValuedModelElementDecorator);
Mvvm.register("model", ["span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "li", "label", "div"], InnerHtmlElementDecorator);
Mvvm.register("options-model", ["select"], SelectOptionsElementDecorator);
Mvvm.register("enabled", ["select", "input", "textarea", "button"], DisableableModelElementDecorator);
Mvvm.register("attribute", ["*"], AttributeElementDecorator);
Mvvm.register("visible", ["*"], VisibleElementDecorator);
Mvvm.register("component-each", ["*"], ComponentEachElementDecorator);
Mvvm.register("force-focus", ["*"], ForceFocusElementDecorator);
Mvvm.register("region", ["*"], RegionDecorator);
Mvvm.register("checkbox-list", ["ul"], CheckboxListDecorator);
