name: CI-Linux
on:
  push:
    branches:
    - 'release/*'
    - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: test
      run: |
        npm install
        npm run install
        npm run build
