name: Release
run-name: Release cut of ${{ github.event.inputs.release_version }}"
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
      next_version:
        description: 'Next Version'
        required: true
jobs:
  cut-release:
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
    - name: Validate semantic version input
      run: |
        RELEASE_VERSION="${{ github.event.inputs.release_version }}"
        NEXT_VERSION="${{ github.event.inputs.next_version }}"
        SEMVER_REGEX="^([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$"

        if [[ ! "$RELEASE_VERSION" =~ $SEMVER_REGEX ]]; then
          echo "Error: Release version '$RELEASE_VERSION' is not a valid semantic version (e.g. 1.2.3, 1.0.0-beta.1)"
          exit 1
        else
          echo "Valid semantic version: $RELEASE_VERSION"
        fi

        if [[ ! "$NEXT_VERSION" =~ $SEMVER_REGEX ]]; then
          echo "Error: Next version '$NEXT_VERSION' is not a valid semantic version (e.g. 1.2.3, 1.0.0-beta.1)"
          exit 1
        else
          echo "Valid semantic version: $NEXT_VERSION"
        fi
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Configure Git User
      run: |
        git config --global user.email "github-actions-automation@cydran.io"
        git config --global user.name "Cydran Actions Automation"
    - name: Setup git auth
      run: |
        git remote set-url origin https://x-access-token:${GIT_AUTH}@github.com/cydran/cydran.git
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
    - name: Commit locks
      run: |
        git add -u 
        git commit -m "Automated Commit - Updated package locks"
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
    - name: Show remote URL
      run: git remote -v
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
    - name: Push changes
      run: |
        git push origin HEAD:master
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
    - name: Run tag version
      run: npx lerna version ${{ github.event.inputs.release_version }} --yes
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
    - name: Run push next version
      run: npx lerna version ${{ github.event.inputs.next_version }}-snapshot --yes --no-git-tag-version
      env:
        GIT_AUTH: ${{ secrets.ACTION_AUTOMATION_TOKEN }}
