name: Release
run-name: Release cut of ${{ github.event.inputs.release_version }}"
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
      next_version:
        description: 'Next Version'
        required: true
jobs:
  cut-release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: test
      run: |
        npm install
        npm run build.release